blank_issues_enabled: false
contact_links:
  - name: Suporte via Discord
    url: https://discord.gg/KEYgM3sB
    about: Suporte em tempo real / chat com a equipe.
  - name: Documentação
    url: https://notion.so/
    about: Documentação - informações sobre o projeto.
