# Baseado no template de issue
name: Solicitação de Funcionalidade
description: Proponha uma funcionalidade ou ideia para este projeto
title: "[FEAT]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para preencher esta solicitação de funcionalidade!
  - type: textarea
    id: wanted-change
    attributes:
      label: Mudança Desejada
      description: Nos diga o que você quer que aconteça.
      placeholder: Descreva a funcionalidade ou mudança que você gostaria de ver implementada...
    validations:
      required: true
  - type: textarea
    id: reason-for-change
    attributes:
      label: Motivo da Mudança
      description: Justifique sua solicitação, por que você quer isso, qual é o benefício.
      placeholder: Explique por que esta funcionalidade seria útil e quais problemas ela resolveria...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Proposta de Alteração no Código
      description: Você tem alguma alteração de código em mente?
      placeholder: Se você já pensou em como implementar isso, compartilhe suas ideias aqui...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Ambiente
      description: |
        exemplos:
          - **SO**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
        - SO:
        - Node:
        - npm:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Algo mais?
      description: |
        Links? Referências? Qualquer coisa que nos dê mais contexto sobre a funcionalidade que você está propondo!

        Dica: Você pode anexar imagens ou arquivos de log clicando nesta área para destacá-la e depois arrastando os arquivos para dentro.
      placeholder: Informações adicionais, links úteis, exemplos de outros projetos...
    validations:
      required: false
