---
name: Relatório de Bug
description: Registre um relatório de bug.
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para preencher este relatório de bug!
  - type: textarea
    id: current-behavior
    attributes:
      label: Comportamento Atual
      description: Nos diga o que acontece ao invés do comportamento esperado.
      placeholder:
        Descreva o que está acontecendo atualmente. Por exemplo, "Ao clicar no botão de salvar, a aplicação trava e
        exibe uma mensagem de erro..."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento Esperado
      description: Nos diga o que deveria acontecer.
      placeholder:
        Descreva o comportamento correto esperado. Por exemplo, "O formulário deveria ser salvo com sucesso e exibir uma
        mensagem de confirmação..."
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Passos Para Reproduzir
      description: Passos para reproduzir o comportamento.
      placeholder: |
        1. Vá para a página '...'
        2. Clique em '...'
        3. Role até '...'
        4. Observe o erro em '...'
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Em quais navegadores você está vendo o problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Saída de log relevante
      description:
        Por favor, copie e cole qualquer saída de log relevante. Isso será automaticamente formatado em código, então
        não é necessário usar crases.
      placeholder: Cole aqui mensagens de erro do console, stack traces ou logs relevantes...
      render: shell
    validations:
      required: false
