---
name: Relatório de Bug
description: Registre um relatório de bug.
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para preencher este relatório de bug!
  - type: textarea
    id: current-behavior
    attributes:
      label: Comportamento Atual
      description: Nos diga o que acontece ao invés do comportamento esperado.
      value: "Um bug aconteceu!"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento Esperado
      description: Nos diga o que deveria acontecer.
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Passos Para Reproduzir
      description: Passos para reproduzir o comportamento.
      placeholder: |
        1. Neste ambiente...
        2. Com esta configuração...
        3. Execute '...'
        4. Veja o erro...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Em quais navegadores você está vendo o problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Saída de log relevante
      description:
        Por favor, copie e cole qualquer saída de log relevante. Isso será automaticamente formatado em código, então
        não é necessário usar crases.
      render: shell
