name: Proposta de recurso
description: Proponha um novo recurso ou ideia para este projeto
labels:
  - feature
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para propor um recurso!
  - type: textarea
    id: problem-description
    attributes:
      label: Sua solicitação de recurso está relacionada a um problema? Por favor, descreva.
      description: 'Uma descrição clara e concisa do problema. Ex: "Sempre fico frustrado quando [...]"'
      placeholder: Descreva o problema...
      rows: 5
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Descreva a solução que você gostaria
      description: Uma descrição clara e concisa do que você quer que aconteça.
      placeholder: Descreva a solução...
      rows: 5
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Descreva as alternativas que você considerou
      description: Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.
      placeholder: Descreva as alternativas...
      rows: 3
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Contexto adicional
      description: Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.
      placeholder: Qualquer outra informação relevante...
      rows: 3
    validations:
      required: false
